[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_TLS_REJECT_UNAUTHORIZED = "0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/.prisma/client/**",
    "node_modules/@prisma/client/**",
    "node_modules/prisma/**",
    "prisma/schema.prisma",
  ]
